### PR TITLE
Add Arduino firmware and readme placeholder

### PR DESCRIPTION
**Pull request by rex-300FeetOut**

### CODE REVIEW

**Comment by dkozel** [comment]
Hi @rexington. Can you add a Readme file in the firmware directory describing the two different firmwares in here?

Also, do we have a copyright license for these firmwares? Adding that now will be easier than later.

**Comment by rex-300FeetOut** [comment]
Good idea @dkozel! I'll add the readme.

@KJ6VU would you say we want the firmware to have a GNU General Public License? If so, I can drop one of those in there.

**Comment by dkozel** [comment]
@rexington I've merged pieces of your pull request into the repository. Beric confirmed the GPL choice so I've added that in.

Marc's modified code also had formatting changes so I've pulled those into a separate changeset, that way we'll be able to see the actual functional changes easily. I don't have hardware on hand to test with tonight so I've staged those changes in https://github.com/HamRadio360/Antenna-Analyzer/pull/2

Thanks for making this pull request, I hadn't been checking the forum so didn't see the improvements available!

**Comment by rex-300FeetOut** [comment]
Awesome! My PR was primarily to see if anything would get merged. Here we go!

Should we close this PR at this point, now that you've taken the necessary pieces?

**Comment by dkozel** [comment]
I've added issues to track the main features that Marc added. I'd like to get the code slightly cleaned up before merging the new features, but yes, we can close this PR.

https://github.com/HamRadio360/Antenna-Analyzer/issues/6
https://github.com/HamRadio360/Antenna-Analyzer/issues/5

**Pull request closed without merging**
